CUDA_VISIBLE_DEVICES=0 ns-train in2n --data ./data/datasets/yonwoo --load-dir outputs/yonwoo/nerfacto/2023-05-16_215645/nerfstudio_models --pipeline.prompt "Give him a cowboy hat" --timestamp cowboy_image_cfg_2dot0 --pipeline.guidance-scale 7.5 --pipeline.image-guidance-scale 2.0 --pipeline.ip2p-device cuda:0
CUDA_VISIBLE_DEVICES=1 ns-train in2n --data ./data/datasets/yonwoo --load-dir outputs/yonwoo/nerfacto/2023-05-16_215645/nerfstudio_models --pipeline.prompt "Give him a cowboy hat" --timestamp cowboy_image_cfg_2dot1 --pipeline.guidance-scale 7.5 --pipeline.image-guidance-scale 2.1 --pipeline.ip2p-device cuda:0
CUDA_VISIBLE_DEVICES=2 ns-train in2n --data ./data/datasets/yonwoo --load-dir outputs/yonwoo/nerfacto/2023-05-16_215645/nerfstudio_models --pipeline.prompt "Give him a cowboy hat" --timestamp cowboy_image_cfg_2dot2 --pipeline.guidance-scale 7.5 --pipeline.image-guidance-scale 2.2 --pipeline.ip2p-device cuda:0
CUDA_VISIBLE_DEVICES=3 ns-train in2n --data ./data/datasets/yonwoo --load-dir outputs/yonwoo/nerfacto/2023-05-16_215645/nerfstudio_models --pipeline.prompt "Give him a cowboy hat" --timestamp cowboy_image_cfg_2dot3 --pipeline.guidance-scale 7.5 --pipeline.image-guidance-scale 2.3 --pipeline.ip2p-device cuda:0

CUDA_VISIBLE_DEVICES=4 ns-train in2n --data ./data/datasets/yonwoo --load-dir outputs/yonwoo/nerfacto/2023-05-16_215645/nerfstudio_models --pipeline.prompt "Give him a beanie" --timestamp beanie_text_cfg_7dot3 --pipeline.guidance-scale 7.3 --pipeline.image-guidance-scale 1.5 --pipeline.ip2p-device cuda:0
CUDA_VISIBLE_DEVICES=5 ns-train in2n --data ./data/datasets/yonwoo --load-dir outputs/yonwoo/nerfacto/2023-05-16_215645/nerfstudio_models --pipeline.prompt "Give him a beanie" --timestamp beanie_text_cfg_7dot1 --pipeline.guidance-scale 7.1 --pipeline.image-guidance-scale 1.5 --pipeline.ip2p-device cuda:0
CUDA_VISIBLE_DEVICES=6 ns-train in2n --data ./data/datasets/yonwoo --load-dir outputs/yonwoo/nerfacto/2023-05-16_215645/nerfstudio_models --pipeline.prompt "Give him a beanie" --timestamp beanie_text_cfg_6dot9 --pipeline.guidance-scale 6.9 --pipeline.image-guidance-scale 1.5 --pipeline.ip2p-device cuda:0
CUDA_VISIBLE_DEVICES=7 ns-train in2n --data ./data/datasets/yonwoo --load-dir outputs/yonwoo/nerfacto/2023-05-16_215645/nerfstudio_models --pipeline.prompt "Give him a beanie" --timestamp beanie_text_cfg_6dot7 --pipeline.guidance-scale 6.7 --pipeline.image-guidance-scale 1.5 --pipeline.ip2p-device cuda:0


# render
CUDA_VISIBLE_DEVICES=0 ns-render --load-config outputs/yonwoo/in2n/cowboy_image_cfg_2dot0/config.yml --traj filename --camera-path-filename data/datasets/yonwoo/camera_paths/2023-05-16_215645.json --output-path renders/yonwoo/cowboy_image_cfg_2dot0.mp4
CUDA_VISIBLE_DEVICES=1 ns-render --load-config outputs/yonwoo/in2n/cowboy_image_cfg_2dot1/config.yml --traj filename --camera-path-filename data/datasets/yonwoo/camera_paths/2023-05-16_215645.json --output-path renders/yonwoo/cowboy_image_cfg_2dot1.mp4
CUDA_VISIBLE_DEVICES=2 ns-render --load-config outputs/yonwoo/in2n/cowboy_image_cfg_2dot2/config.yml --traj filename --camera-path-filename data/datasets/yonwoo/camera_paths/2023-05-16_215645.json --output-path renders/yonwoo/cowboy_image_cfg_2dot2.mp4
CUDA_VISIBLE_DEVICES=3 ns-render --load-config outputs/yonwoo/in2n/cowboy_image_cfg_2dot3/config.yml --traj filename --camera-path-filename data/datasets/yonwoo/camera_paths/2023-05-16_215645.json --output-path renders/yonwoo/cowboy_image_cfg_2dot3.mp4

CUDA_VISIBLE_DEVICES=4 ns-render --load-config outputs/yonwoo/in2n/beanie_text_cfg_7dot3/config.yml --traj filename --camera-path-filename data/datasets/yonwoo/camera_paths/2023-05-16_215645.json --output-path renders/yonwoo/beanie_text_cfg_7dot3.mp4
CUDA_VISIBLE_DEVICES=5 ns-render --load-config outputs/yonwoo/in2n/beanie_text_cfg_7dot1/config.yml --traj filename --camera-path-filename data/datasets/yonwoo/camera_paths/2023-05-16_215645.json --output-path renders/yonwoo/beanie_text_cfg_7dot1.mp4
CUDA_VISIBLE_DEVICES=6 ns-render --load-config outputs/yonwoo/in2n/beanie_text_cfg_6dot9/config.yml --traj filename --camera-path-filename data/datasets/yonwoo/camera_paths/2023-05-16_215645.json --output-path renders/yonwoo/beanie_text_cfg_6dot9.mp4
CUDA_VISIBLE_DEVICES=7 ns-render --load-config outputs/yonwoo/in2n/beanie_text_cfg_6dot7/config.yml --traj filename --camera-path-filename data/datasets/yonwoo/camera_paths/2023-05-16_215645.json --output-path renders/yonwoo/beanie_text_cfg_6dot7.mp4
